stages:
  - verify
  - prepare
  - build
  - deploy
  - release

# If you are looking for a place where to add 'UNITY_LICENSE_FILE' and other secrets, please visit your project's gitlab page:
# settings > CI/CD > Variables instead
variables:
  MAJOR: 0
  MINOR: 0
  PATCH: $CI_PIPELINE_IID  # The version is incremented per pipeline.

  RELEASE_TAG: v$MAJOR.$MINOR.$PATCH     # v0.0.133
  BUILD_NAME: ubss-$MAJOR-$MINOR-$PATCH  # ubss-0-0-133
  PACKAGE_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/build/android-${RELEASE_TAG}/${BUILD_NAME}.apk

  IMAGE: unityci/editor # https://hub.docker.com/r/unityci/editor
  IMAGE_VERSION: 3 # This will automatically use latest v3.x.x, see https://github.com/game-ci/docker/releases
  UNITY_DIR: $CI_PROJECT_DIR/development/project_urban  # this needs to be an absolute path. Defaults to the root of your tree.
  # You can expose this in Unity via Application.version
  VERSION_NUMBER_VAR: $CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID-$CI_JOB_ID
  VERSION_BUILD_VAR: $CI_PIPELINE_IID


# this uses DOCKER_AUTH_CONFIG from ci variables
image: europe-west1-docker.pkg.dev/android-gitlab-runner/ubss-docker-repo/$IMAGE:$UNITY_VERSION-android-$IMAGE_VERSION


get-unity-version:
  image: alpine
  stage: prepare
  variables:
    GIT_DEPTH: 1
  script:
    - echo UNITY_VERSION=$(cat $UNITY_DIR/ProjectSettings/ProjectVersion.txt | grep "m_EditorVersion:.*" | awk '{ print $2}') | tee prepare.env
  artifacts:
    reports:
      dotenv: prepare.env

.unity_before_script: &unity_before_script
  before_script:
    - chmod +x ./development/ci/before_script.sh && ./development/ci/before_script.sh
  needs:
    - job: get-unity-version
      artifacts: true

.unity_after_script: &unity_after_script
  after_script:
    - chmod +x ./development/ci/return_license.sh && ./development/ci/return_license.sh

.cache: &cache
# put stuff into the cache only on the main branch, all others pull. That way, we can always use the same cache. (maybe)
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        POLICY: pull-push
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      variables:
        POLICY: pull
  cache:
    key: "$CI_PROJECT_NAME"
    policy: $POLICY
    paths:
      - $UNITY_DIR/Library/
      - $UNITY_DIR/.utmp/

.license: &license
  rules:
    - if: '$UNITY_LICENSE != null || $UNITY_SERIAL != null'
      when: always

.unity_defaults: &unity_defaults
  <<:
    - *unity_before_script
    - *cache
    - *license
    - *unity_after_script

.build: &build
  stage: build
  <<: *unity_defaults
  script:
    - chmod +x ./development/ci/build.sh && ./development/ci/build.sh
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Builds/


build-android:
  <<: *build
  variables:
    BUILD_TARGET: Android
    BUILD_APP_BUNDLE: "false"
  tags:
    - build-android


publish:
  stage: deploy
  image: bash:latest
  script:
    - |
      apk add curl
      curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "${CI_PROJECT_DIR}/Builds/Android/${BUILD_NAME}.apk" "${PACKAGE_URL}"

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $TAG"
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$RELEASE_TAG'
    name: 'Release $RELEASE_TAG'
    description: '$CI_COMMIT_MESSAGE'
    ref: '$CI_COMMIT_SHA'                          # The tag is created from the pipeline SHA.
    assets:
      links:
        - name: android-$RELEASE_TAG/$BUILD_NAME.apk
          url: $PACKAGE_URL
          link_type: 'package'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

